# -*- coding: utf-8 -*-
"""Hello_World.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TcV4eeSxRygbQYz0EokwZoTxlY-iGo3
"""

print ("Hello World ")

print ("Welcome to CIS 3120")

gradeFinal = input("Please enter your final grade: ")
output = "your final grade is " + gradeFinal
print (output)

letterGrade = gradeFinal
if letterGrade >= "90":
    print ("your letter grade is A")
elif letterGrade >= "80":
    print ("your letter grade is B")
elif letterGrade >= "70":
    print ("your letter grade is C")
elif letterGrade >= "60":
    print ("your letter grade is D")

